install: npm install
dist: trusty
addons:
  chrome: stable
language: node_js
cache:
  directories:
  - node_modules
env:
  global:
  - secure: Lx0kRWYiS37utb5BoqkGIMNshSNseunur+aSzF20IsudVV3lyG+Gy4NbWYdeGBBOsoQ5msV3J9WRVfhXeou+MH27RHkv7TAYMwQh9E2mMSDcfsz4DITvGxQEVZGuY6RZY78PkF8Lk+y0AvQTxRc+mJkKl7k+C08wWg6tWDP7qdh2Af783K/ME0+qvRgk8XE6B520pxq1UMUkChmbZ8fvn/RiKoz1wdb3brwTR9qsyx9J6OzOdj7+Z9o77NzgxcUK/xald+Nb57cSBI7aX0vf5B+1tQKqhzM82G4uYuOMMeNYf5pHTXTLzwMxPahZn9tsdv5VsBFz7BNsu/syAkwkaYf0ok5frfwoWCJpXNIEqNitl0Rt7jMdGriP6m2lY6a5zNCCfjG5FMScdarOKeMSf5T2c4Z/6HBrPLmLnpguNGSiE3oOXhw+U6CX3ULB89UYaGREgpyLPwVfjGQA9aakWl/bOGWjwTrmgdbXvSxA/gm7oO29jpW4pUbWhzA8IGaFP1e/hb75cbVHtbntA9aHyKYilVHmO90oVkOA9wTBJCjvSDVfsDkz7aIC7Y2+MOUesQp6SqpKAXXole0Z5YQFdR2wqOZaWoWOHyjbNV6IlPfP4l7vw5hFhqL8coA8zem64aTw7ajUiVoI14PW2EdPFTVG4c0dsilhGEQ0owjq0jw=
  - secure: jh5w/If7TCWubM/h1HCtpoSeKvUV+bHkomndIZNSdSY30hzI7bZEBv5WrOAopwfUEtOHbefWdsuC9AURDx7cHbg4P+hfnbiOBZenTWzGzV2VCTRINmBVNGZjwmpTvYtIBra2SfnMwNvROqDgtuf6LkZOhBXRABr6svV1Hi+wP0GR0wJE5h5dU6wZ3ZCKYlU6sFjqY/uWJ1DwnhMXb3GXo4qMfPTrOh1Ds2PyE9NeoapT8BHfRPD8+ogIAj0ZcFmPYlHW6hMiNxzPMyBFwwmsmdXKrDBItdb1FOl5TlHBxnb6wyVckwCcYWk/HJTqaHH6K46+IIeU+BOnIzOsOlGaDWksxnwOhrS6gxmdOJDqPfNAU4UCE91mI2o0xVb1WhRvfU/RHxp/tNpnaHtXx7NewwHQxUqvR6QsyY9ldTRF5iagSzRqkR3GNXEey4QbystrvHBCRKOoePqGbfjeO3BDkLdMrz8UyIb1AZSu9RgAxgYjHTF3AnJb9e+1+2eBWuUtsag75WZiJBVj8iKPIEuqN0ZWJ/lp6KlaymR9A6FrzWJ5DRLuftaMNZRem3M+0z8lPEF4X4Jpmqx6InL0it/FdMfI2vej34N6bYJuUCrVgttG2EPUliF2MUJIDfgGXvfttRHMLkUhu7iob5Wm+hdYqm3sUkn7Net3DmOj/NsMQr8=
